services:
  - type: web
    name: spookytube
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: spookytube-db
          property: connectionString

databases:
  - name: spookytube-db
    databaseName: spookytube
    user: spookytube_user
